### PR TITLE
Enhance song variation through random playlist creation 

### PR DESCRIPTION
**Pull request by githtz**
Imrpove song variation by creating random playlists instead of chosing a random song each time the next_song method is called. 
On first call of next_song a random playlist will be created and stored. The next song will be popped of the randomized playlist until there are no songs left to play. Once that happens a new randomized playlist will be created, containing all songs except the last one played.
~~This PR ensures that all songs are played at least once before a song that was played already gets played again.~~

Also fixes a small bug that occured by trying to read the first sign of each line on import of the songs.txt file.

### CODE REVIEW

**Comment by orwell96** [comment]
Have you tested? Else looks OK.

**Comment by githtz** [comment]
Yes, I've been using it for a few hours. Tried it with three tracks first to confirm it works properly and then used a larger playlist of about 40 tracks. You can verify it yourself of course!

**Comment by orwell96** [comment]
Ok

**Comment by orwell96** [comment]
I will merge it as soon as possible

**Comment by orwell96** [comment]
Hm, finally tested this...
In my opinion, this has little advantage as it is implemented now, because the case A - B - A can still happen when the list turns over. Additionally, there's a mistake in the implementation (nums[i] = i makes a hole in the list)

**Comment by orwell96** [comment]
Better would be to insert a song just played randomly somewhere in the upper half of a queue, so that it comes earliest after N/2 songs

**Comment by githtz** [comment]
I thought it would be better to have something like A-B-A once instead of A-A-B-A.
For your proposed solution there's imho a good chance a certain song will play almost never because others are inserted right before it alot of times. Nevermind though. I acceppt defeat.

**Pull request closed without merging**
